#!/bin/bash

# function handle_opts

echo "#> creating data-only container: grappa-src"
# setup data container with grappa source in volume '/grappa'
# - pulls the grappa-base repository from the registry
docker run --privileged --name grappa-src -v /grappa busybox

echo "#> cloning into container: grappa-src"
docker run --privileged --volumes-from grappa-src uwsampa/grappa -c \
  'git clone https://github.com/uwsampa/grappa.git'
